ALTER TABLE restaurants
  ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(10,2) NOT NULL DEFAULT 2.90,
  ADD COLUMN IF NOT EXISTS delivery_time_min INTEGER NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS delivery_time_max INTEGER NOT NULL DEFAULT 35;
